dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_messaging: ^14.7.9
  http: ^1.1.2
  url_launcher: ^6.2.5
  provider: ^6.1.1
  either_dart: ^1.0.0
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  logger: ^2.0.2
